// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          'this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:web:demo-app-id',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    authDomain: 'diurouteexplorer.firebaseapp.com',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:android:1011f542f2ec42f5a09e21',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:ios:demo-app-id',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
    iosBundleId: 'com.example.diuRouteExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:ios:demo-app-id',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
    iosBundleId: 'com.example.diuRouteExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:web:demo-app-id',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    authDomain: 'diurouteexplorer.firebaseapp.com',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCI6YfiL25Mk9NDd-ang5EItzUsHDTRQXw',
    appId: '1:1010202081140:web:demo-app-id',
    messagingSenderId: '1010202081140',
    projectId: 'diurouteexplorer',
    authDomain: 'diurouteexplorer.firebaseapp.com',
    storageBucket: 'diurouteexplorer.firebasestorage.app',
  );
}
